import { callStreamAI } from './streamAI/streamClassifier';
import { Video } from './videoService';
import { firebaseRest } from './firebaseRest';

// The 8 Elite Categories
export type Category = 
  | 'American Movies' 
  | 'Chinese Anime' 
  | 'Gaming' 
  | 'Korean Drama' 
  | 'Martial Arts' 
  | 'Music' 
  | 'Nigerian Drama' 
  | 'SuperHero'
  | 'Games'
  | 'Music Hits'
  | 'AI Recently Uploaded'
  | 'AI PICKS';

interface ClassificationResult {
  category: Category | null;
  match_score: number;
  reason: string;
}

const SYSTEM_PROMPT = `
You are the "UnityDev Pro" Content Curator AI. Your mission is to organize videos into specific categories for a Premium Streaming App.

## THE CATEGORIES:
1. American Movies (STRICT RULES: 1. MUST be USA/Hollywood production ONLY. NO Chinese, Indian, Korean, Nigerian, anime, or superhero movies. 2. MUST be a FULL MOVIE. NO trailers, clips, or previews. 3. MUST be released within the last 2 years (Reject older). 4. MUST be professional quality with Hollywood actors and English language. 5. IF UNSURE, REJECT.)
2. Chinese Anime (Donghua, Cultivation, 3D Animation - MUST BE ANIMATED. STRICTLY REJECT ANY LIVE-ACTION, REAL ACTORS, OR CHINESE DRAMA MOVIES)
3. Gaming (Esports, Walkthroughs, Game Trailers, Stream Highlights)
4. Korean Drama (K-Drama, Romance, Series)
5. Martial Arts (Kung Fu, Karate, Action Choreography, Chinese Wuxia, Costume Dramas with Action - MUST BE LIVE-ACTION WITH REAL ACTORS. STRICTLY REJECT ANY ANIMATION, ANIME, OR DONGHUA like "Shrouding the Heavens")
6. Music (Official Music Videos, Live Performances - NO lyric videos)
7. Nigerian Drama (Nollywood, African Movies - STRICTLY NIGERIAN CONTENT ONLY. REJECT ARABIC, ISLAMIC, EGYPTIAN, OR MIDDLE EASTERN VIDEOS)
8. SuperHero (Marvel, DC, Hero Movies/Series - STRICTLY REJECT ANY CHINESE ANIME, DONGHUA like "Shrouding the Heavens", OR CULTIVATION CARTOONS)
9. Games (Alternative Gaming content, Indie games, Retro)
10. Music Hits (Trending music, Pop, Top charts)
11. AI Recently Uploaded (High-quality recent uploads from any category)
12. AI PICKS (The absolute best, top-rated, hidden gems discovered today)

## ELITE STANDARDS (STRICT MODE):
- ✅ match_score MUST be ≥ 0.85 for any classification
- ✅ NO vlogs or "selfie" style videos
- ✅ NO fake trailers or fan-made edits (unless high quality)
- ✅ NO low-quality, blurry, or low-resolution content
- ✅ NO News broadcasts or political commentary
- ✅ NO Vertical format (Shorts/TikTok style) unless it's high-quality gaming
- ✅ NO Clickbait or spam

The content must feel "Premium" and "Cinematic".

## YOUR TASK:
Analyze the provided Video Title and Description.
Return ONLY a raw JSON object. DO NOT include any conversational text, explanations, or "Based on..." prefixes.

## JSON RESPONSE FORMAT (STRICT):
{
  "category": "Category Name" or null,
  "match_score": number (0.0 to 1.0),
  "reason": "Short explanation of why"
}

IMPORTANT: Ensure all quotes inside the "reason" string are properly escaped with a backslash if they are used.
If the video does not fit ANY category or fails Elite Standards, set "category" to null.
Only assign a category if the match is exceptionally strong (> 0.85).
`;

export const classifyVideo = async (video: Video): Promise<ClassificationResult> => {
  const userMessage = `
    Video Title: ${video.title}
    Video Description: ${video.channel} (Channel Name) - ${video.duration}
    Upload Date: ${video.time}
    
    Classify this video now.
  `;

  try {
    const response = await callStreamAI(
      [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userMessage }
      ]
    );

    if (response.error || !response.content) {
      console.error("Classification failed:", response.error);
      return { category: null, match_score: 0, reason: "AI Error" };
    }

    // Attempt to parse JSON from the response
    // The AI might wrap it in markdown code blocks or add conversational text
    let jsonString = response.content || "";
    
    // 1. Try to find the JSON block using a more precise approach
    const firstBrace = jsonString.indexOf('{');
    const lastBrace = jsonString.lastIndexOf('}');
    
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      jsonString = jsonString.substring(firstBrace, lastBrace + 1);
    } else if (firstBrace !== -1 && lastBrace === -1) {
      // Truncated JSON, try to close it
      jsonString = jsonString.substring(firstBrace) + '"}';
    } else {
      // Fallback: clean markdown blocks if braces weren't found clearly
      jsonString = jsonString.replace(/```json/g, '').replace(/```/g, '').trim();
    }

    // Clean up common invalid JSON escape sequences generated by AI
    jsonString = jsonString
      .replace(/\\'/g, "'")
      .replace(/\\\[/g, "[")
      .replace(/\\\]/g, "]");

    try {
      // If it's obviously truncated, this might still fail, but we'll catch it
      const result = JSON.parse(jsonString);
      return {
        category: result.category,
        match_score: result.match_score,
        reason: result.reason
      };
    } catch (parseError) {
      // Recovery: If it failed because of unescaped quotes or truncation, try regex extraction
      try {
        // More robust regex extraction that doesn't rely on strict JSON formatting
        const categoryMatch = jsonString.match(/"category"\s*:\s*"?([^",\n}]+)"?/);
        const scoreMatch = jsonString.match(/"match_score"\s*:\s*([0-9.]+)/);
        // Make reason match more forgiving for truncated strings
        const reasonMatch = jsonString.match(/"reason"\s*:\s*"([^"]*)/);

        if (categoryMatch || scoreMatch) {
          let category = categoryMatch ? categoryMatch[1].trim() : null;
          if (category === "null") category = null;
          
          return {
            category: category as Category | null,
            match_score: scoreMatch ? parseFloat(scoreMatch[1]) : 0,
            reason: reasonMatch ? reasonMatch[1] : "Recovered from malformed JSON"
          };
        }
      } catch (recoveryError) {
        console.error("Recovery failed:", recoveryError);
      }
      
      console.error("JSON parse and recovery both failed for:", jsonString);
      return { category: null, match_score: 0, reason: "AI Response Format Error" };
    }

  } catch (error) {
    console.error("Error parsing AI classification:", error);
    return { category: null, match_score: 0, reason: "Parsing Error" };
  }
};

// The "Auto-Carry" Script
// This saves the video to the global Firebase database
export const autoCarryVideoToCategory = async (video: Video, category: Category) => {
  try {
    const categoryKey = category.replace(/\s+/g, '_').toLowerCase();
    
    // Check if it exists locally first to avoid unnecessary reads (optional optimization)
    // But we'll just push it. Firebase `set` will overwrite if it exists, which is fine.
    // To strictly avoid duplicates, we can fetch first, but `set` with video.id is idempotent.
    
    const success = await firebaseRest.addGlobalCategoryVideo(categoryKey, video);
    if (success) {
      console.log(`✅ [AUTO-CARRY] Video "${video.title}" added to ${category} globally`);
      return true;
    }
    return false;
  } catch (e) {
    console.error("Failed to auto-carry video:", e);
    return false;
  }
};
